services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=passwordd
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_ROOT_PASSWORD= rootpassword
    volumes:
      - "./db:/docker-entrypoint-initdb.d"

  www:
    image: frainnyy/webook:latest
    build: .
    volumes:
      - "./src:/var/www/html"
    ports:
      - 3000:80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 5432:80
    environment:
     - PMA_HOST=db
     - PMA_PORT=3306