version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      - mynetwork

  www:
    image: frainnyy/webook:latest
    build: .
    volumes:
      - "./src:/var/www/html"
    ports:
      - 3000:80
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 5432:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
